version: "1.0.0"
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT}:5432"
